export { KioskDashboard } from './KioskDashboard'
export { Screen1Identify } from './Screen1Identify'
export { Screen2SymptomPicker } from './Screen2SymptomPicker'
export { Screen2Converse } from './Screen2Converse'
export { Screen3Scan } from './Screen3Scan'
export { Screen4Consult } from './Screen4Consult'